"""Generated documentation: one README per case and the gallery in the top README.

Everything here is a pure function of the committed data, so ``emref check`` can
rebuild it and fail when the committed copy is stale.
"""
from __future__ import annotations

from .case import Case
from .stack import ROOT

GALLERY_BEGIN = "<!-- gallery:begin (generated by `python -m emref build`, do not edit) -->"
GALLERY_END = "<!-- gallery:end -->"
CANDIDATES_BEGIN = "<!-- candidates:begin (generated by `python -m emref build`, do not edit) -->"
CANDIDATES_END = "<!-- candidates:end -->"
LAYOUT_SVG = "layout.svg"
SPARAMS_SVG = "sparams.svg"


def _ghz(f: float) -> str:
    return f"{f / 1e9:g}"


def _num(x) -> str:
    return "-" if x is None else f"{x:g}"


def _source_links(src: dict) -> str:
    parts = [f'<a href="{src["url"]}">source</a>']
    if "doi" in src:
        parts.append(f'<a href="https://doi.org/{src["doi"]}">doi:{src["doi"]}</a>')
    parts.append(src["license"])
    return " | ".join(parts)


def _prov(entry: dict) -> str:
    p = entry["provenance"]
    if isinstance(p, str):
        return p
    rest = ", ".join(f"{k}: {v}" for k, v in p.items() if k != "default")
    return f"{p['default']} ({rest})"


def status_line(case: Case) -> str:
    label, reasons = case.status()
    if label == "complete":
        return "**complete**"
    noun = "open questions" if label == "incomplete" else "values not stated by the source"
    return f"**{label}**, {len(reasons)} {noun}"


def _boundary(b) -> str:
    return b if isinstance(b, str) else f"conductor, sigma {b['sigma_s_per_m']:g} S/m"


def _model(d: dict) -> str:
    if d.get("model", "constant") == "constant":
        return "constant"
    return (f"Djordjevic-Sarkar, at {_ghz(d['f_ref_hz'])} GHz, "
            f"{d['f_low_hz']:g} to {d['f_high_hz']:g} Hz")


def _z0(z0) -> str:
    return "line Z0" if z0 == "line" else f"{z0:g}"


def summary_line(case: Case) -> str:
    f_min, f_max = case.band
    return (f"{case.raw['domain']} | {case.raw['family']} | stack `{case.stack.name}` | "
            f"{len(case.ports())} ports | {_ghz(f_min)}-{_ghz(f_max)} GHz")


def case_readme(case: Case) -> str:
    src, stack = case.raw["source"], case.stack
    label, reasons = case.status()
    lines = [f"# {case.title}", "", summary_line(case), "", f"Status: {status_line(case)}", "",
             '<table><tr>',
             f'<td width="50%"><img src="{LAYOUT_SVG}" width="100%"></td>',
             f'<td width="50%"><img src="{SPARAMS_SVG}" width="100%"></td>',
             '</tr></table>', "",
             "## Source", "",
             f"- Authors: {', '.join(src['authors'])}",
             f"- URL: {src['url']}" + (f" (commit `{src['commit']}`)" if "commit" in src else "")]
    if "doi" in src:
        lines.append(f"- DOI: [{src['doi']}](https://doi.org/{src['doi']})")
    lines.append(f"- License: {src['license']}")
    if "citation" in src:
        lines.append(f"- Cite as: {src['citation']}")

    lines += ["", "## Measurements", "",
              "| label | file | reference plane | calibration |", "|---|---|---|---|"]
    for m in case.measurements():
        lines.append(f"| {m.label} | `{m.meta['file']}` | {m.meta['reference_plane']} | "
                     f"{m.meta['calibration']} |")

    lines += ["", "## Ports", "", "| port | kind | drives | returns to | segment [um] | de-embed [um] | Z0 [Ohm] |",
              "|---|---|---|---|---|---|---|"]
    for p in case.ports():
        (ax, ay), (bx, by) = p.segment
        lines.append(f"| {p.name} | {p.kind} | {p.layer} | {p.reference} | "
                     f"({ax:g}, {ay:g}) - ({bx:g}, {by:g}) | {p.deembed_um:g} | {_z0(p.z0_ohm)} |")

    lines += ["", f"## Stack `{stack.name}`", "",
              f"Bottom boundary: {_boundary(stack.boundaries['bottom'])}, top boundary: "
              f"{_boundary(stack.boundaries['top'])}. z is absolute from the bottom of the lowest "
              "dielectric.", "",
              "| dielectric | z [um] | er | tan d | model | sigma [S/m] | provenance |",
              "|---|---|---|---|---|---|---|"]
    for d, lo, hi in reversed(stack.dielectric_spans()):
        lines.append(f"| {d['name']} | {lo:g} - {hi:g} | {d['er']:g} | {d['tand']:g} | "
                     f"{_model(d)} | {_num(d.get('sigma_s_per_m'))} | {_prov(d)} |")
    lines += ["", "| conductor | kind | GDS | z [um] | sigma [S/m] | provenance |",
              "|---|---|---|---|---|---|"]
    for c in sorted(stack.conductors, key=lambda c: -c["z_um"][0]):
        sigma = "PEC" if c.get("pec") else f"{c['sigma_s_per_m']:g}"
        lines.append(f"| {c['name']} | {c['kind']} | {c['gds'][0]}/{c['gds'][1]} | "
                     f"{c['z_um'][0]:g} - {c['z_um'][1]:g} | {sigma} | {_prov(c)} |")
    if stack.conformal:
        lines += ["", "| conformal dielectric | over | er | tan d | top [um] | side [um] | provenance |",
                  "|---|---|---|---|---|---|---|"]
        for s in stack.conformal:
            lines.append(f"| {s['name']} | {s['over']} | {s['er']:g} | {s['tand']:g} | "
                         f"{s['top_um']:g} | {s['side_um']:g} | {_prov(s)} |")
    if "notes" in stack.raw:
        lines += ["", stack.raw["notes"].strip()]

    results = case.results()
    if results:
        lines += ["", "## Solver results", "", "| result | tool | version | author |",
                  "|---|---|---|---|"]
        for name, meta, _ in results:
            lines.append(f"| {name} | {meta['tool']} | {meta['version']} | {meta['author']} |")
    if "notes" in case.raw:
        lines += ["", "## Notes", "", case.raw["notes"].strip()]
    if label == "incomplete":
        lines += ["", "## Open questions", ""] + [f"- {q}" for q in reasons]
    elif label == "reconstructed":
        lines += ["", "## Values not stated by the source", "",
                  "Reconstructed, fitted or assumed; see the stack notes for how.", ""]
        lines += [f"- {r}" for r in reasons]
    lines += ["", "Generated by `python -m emref build`. Do not edit by hand.", ""]
    return "\n".join(lines)


def gallery(cases: list[Case]) -> str:
    rows = [GALLERY_BEGIN, "", "<table>"]
    for c in cases:
        d = f"cases/{c.id}"
        rows += ["<tr>",
                 f'<td width="50%"><a href="{d}"><img src="{d}/{LAYOUT_SVG}" width="100%"></a></td>',
                 f'<td width="50%"><img src="{d}/{SPARAMS_SVG}" width="100%"><br>'
                 f'<a href="{d}"><b>{c.title}</b></a><br>'
                 f"{summary_line(c).replace('`', '')}<br>"
                 f"{status_line(c).replace('**', '')}<br>{_source_links(c.raw['source'])}</td>",
                 "</tr>"]
    rows += ["</table>", "", GALLERY_END]
    return "\n".join(rows)


def candidates_table(candidates: list[dict]) -> str:
    rows = [CANDIDATES_BEGIN, "", "| source | domain | license | blocked by | missing |",
            "|---|---|---|---|---|"]
    for c in candidates:
        link = f"[{c['name']}]({c['url']})"
        rows.append(f"| {link} | {c['domain']} | {c['license']} | {c['blocker']} | "
                    f"{c['missing']} |")
    rows += ["", CANDIDATES_END]
    return "\n".join(rows)


def _replace(text: str, begin: str, end: str, body: str) -> str:
    head, rest = text.split(begin, 1)
    return head + body + rest.split(end, 1)[1]


def top_readme(cases: list[Case], candidates: list[dict]) -> str:
    text = (ROOT / "README.md").read_text(encoding="utf-8")
    text = _replace(text, GALLERY_BEGIN, GALLERY_END, gallery(cases))
    return _replace(text, CANDIDATES_BEGIN, CANDIDATES_END, candidates_table(candidates))
